// GENERATED by scripts/codegen/build-commercial-claims.mjs — DO NOT EDIT.
// Regenerate: node scripts/codegen/build-commercial-claims.mjs
//
// The commercial registry is separate from the residential one by design. The
// two verticals hold different evidence and must not share vocabulary, so they
// do not share a generated module either.

export interface CommercialSource {
  title: string;
  url: string;
  publisher: string;
  tier: number;
}

export interface CommercialClaim {
  id: string;
  claim: string;
  quote: string | null;
  assetClasses: string[];
  entities: string[];
  topics: string[];
  confidence: string;
  jurisdiction: string | null;
  verifiedOn: string;
  /** CURRENT unless the claim describes a fixed past period. Rendered when not CURRENT. */
  temporalStatus: string | null;
  freshness: string | null;
  sources: CommercialSource[];
}

export const commercialClaims: CommercialClaim[] = [
  {
    "id": "boise-i1-purpose",
    "claim": "Boise's I-1 zoning district is intended to accommodate light manufacturing, assembly, fabrication and technology-related uses that may require significant transportation services but typically do not operate at night, and are generally compatible with nearby commercial and residential areas given substantial buffering and screening.",
    "quote": "The I-1 zoning district is intended to accommodate light manufacturing, assembly, fabrication, and technology-related land uses that may require significant transportation services but that typically do not operate during nighttime hours and are generally compatible with nearby commercial and residential areas when accompanied by substantial buffering, screening, and standards designed to mitigate impacts.",
    "assetClasses": [
      "industrial"
    ],
    "entities": [
      "city:boise-city"
    ],
    "topics": [
      "zoning",
      "industrial",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Boise, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": null,
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Industrial Light (I-1) Zoning District — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/industrial-light/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      }
    ]
  },
  {
    "id": "boise-i2-purpose-separation",
    "claim": "Boise's I-2 zoning district accommodates general industrial activity with greater impacts than I-1 — including uses needing significant heavy transportation and uses that frequently operate at night — and the code states the district should be separated from commercial or residential development.",
    "quote": "The I-2 zoning district is intended to accommodate general industrial activity with greater impacts than those in the I-1 zoning district, including uses that require significant heavy transportation services, uses that frequently operate during nighttime hours, and uses that require additional standards to protect health, safety, or general welfare. The I-2 zoning district should be separated from commercial or residential development.",
    "assetClasses": [
      "industrial"
    ],
    "entities": [
      "city:boise-city"
    ],
    "topics": [
      "zoning",
      "industrial",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Boise, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": null,
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Industrial Heavy (I-2) Zoning District — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/industrial-heavy/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      }
    ]
  },
  {
    "id": "boise-industrial-height-varies-by-district",
    "claim": "Boise's industrial districts do not share a height standard. I-1 Light and I-2 Heavy cap building height at 55 feet with no qualification attached. I-3 Industrial Technology permits 150 feet, but that height is not free-standing: it is controlled by a 45 degree angle of bulk plan measured from all exterior property lines.",
    "quote": "Controlled by a 45 degree angle of bulk plan from all exterior property lines up to the maximum height of 150 feet.",
    "assetClasses": [
      "industrial"
    ],
    "entities": [
      "city:boise-city"
    ],
    "topics": [
      "zoning",
      "industrial",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Boise, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": null,
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Boise City Code Tables 11-02.27, 11-02.29, 11-02.31 — I-1, I-2 and I-3 Lot and Building Standards",
        "url": "https://codelibrary.amlegal.com/codes/boise_id/latest/boise/0-0-0-65657",
        "publisher": "City of Boise (American Legal Publishing)",
        "tier": 1
      }
    ]
  },
  {
    "id": "boise-industrial-interstate-parking-setback",
    "claim": "Boise requires a larger parking setback from Interstate frontage in the heavy industrial district than in the light one: any yard adjacent to I-84 or I-184 carries a 10-foot parking setback in I-1 and 20 feet in I-2.",
    "quote": "Any Yard Adjacent to Interstate (I-84 & I-184) 10 ft.",
    "assetClasses": [
      "industrial"
    ],
    "entities": [
      "city:boise-city"
    ],
    "topics": [
      "zoning",
      "industrial",
      "access"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Boise, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": null,
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Industrial Light (I-1) Zoning District — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/industrial-light/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      },
      {
        "title": "Industrial Heavy (I-2) Zoning District — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/industrial-heavy/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      }
    ]
  },
  {
    "id": "boise-i2-street-frontage-minimum",
    "claim": "Boise's I-2 heavy industrial district sets a minimum street frontage of 30 feet, where I-1 sets none.",
    "quote": "LOT STANDARDS Lot Area (minimum) N/A Street Frontage (minimum) 30 ft.",
    "assetClasses": [
      "industrial"
    ],
    "entities": [
      "city:boise-city"
    ],
    "topics": [
      "zoning",
      "industrial",
      "access",
      "land"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Boise, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": null,
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Industrial Heavy (I-2) Zoning District — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/industrial-heavy/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      }
    ]
  },
  {
    "id": "idaho-multifamily-boundary-is-not-one-boundary",
    "claim": "Idaho and Ada County do not use a single definition of where residential property ends and multifamily or commercial begins. At least three systems draw the line differently: county ASSESSMENT treats residential as up to four units and routes apartments to commercial appraisers; the property condition DISCLOSURE act applies to one to four dwelling units; and the domestic WATER statute excludes apartments, condominiums and similar multiple-dwelling developments generally rather than at a unit count.",
    "quote": null,
    "assetClasses": [
      "multifamily"
    ],
    "entities": [
      "county:ada",
      "state:id"
    ],
    "topics": [
      "multifamily",
      "assessment",
      "disclosure",
      "water",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Ada County, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": null,
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Real & Manufactured Property Assessment — Ada County Assessor",
        "url": "https://adacounty.id.gov/assessor/property-assessments-records/real-manufactured-property-assessment/",
        "publisher": "Ada County Assessor",
        "tier": 1
      },
      {
        "title": "Idaho Code § 55-2504 — Property condition disclosure required",
        "url": "https://legislature.idaho.gov/statutesrules/idstat/title55/t55ch25/sect55-2504/",
        "publisher": "Idaho State Legislature",
        "tier": 1
      },
      {
        "title": "Idaho Code § 42-111 — Domestic purposes defined",
        "url": "https://legislature.idaho.gov/statutesrules/idstat/title42/t42ch1/sect42-111/",
        "publisher": "Idaho State Legislature",
        "tier": 1
      }
    ]
  },
  {
    "id": "ada-apartments-valued-by-commercial-appraisers",
    "claim": "Ada County's commercial appraisers, not its residential appraisers, value apartments and high-density residential — alongside office, retail and industrial.",
    "quote": "Our team of commercial appraisers handle valuation for all commercial property types, including, office, retail, industrial, and high-density residential (apartments) uses.",
    "assetClasses": [
      "multifamily",
      "office",
      "retail",
      "industrial"
    ],
    "entities": [
      "county:ada"
    ],
    "topics": [
      "assessment",
      "multifamily",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Ada County, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": null,
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Assessor — Ada County",
        "url": "https://adacounty.id.gov/assessor/",
        "publisher": "Ada County Assessor",
        "tier": 2
      }
    ]
  },
  {
    "id": "ada-commercial-assessment-uses-income",
    "claim": "Ada County develops commercial assessments using data on construction costs, market sales and income production; the residential approach described alongside it relies on construction costs, sales and, where applicable, rental information.",
    "quote": "Data pertaining to construction costs, market sales, and income-production is used to develop commercial assessments.",
    "assetClasses": [
      "multifamily",
      "office",
      "retail",
      "industrial"
    ],
    "entities": [
      "county:ada"
    ],
    "topics": [
      "assessment",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Ada County, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": null,
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Real & Manufactured Property Assessment — Ada County Assessor",
        "url": "https://adacounty.id.gov/assessor/property-assessments-records/real-manufactured-property-assessment/",
        "publisher": "Ada County Assessor",
        "tier": 1
      }
    ]
  },
  {
    "id": "ada-assessment-market-value-jan-1-commercial",
    "claim": "Every non-exempt commercial property in Ada County is assessed at market value as of January 1, on the same annual cycle and the same five-year physical inspection requirement as residential property.",
    "quote": "Idaho law requires that all non-exempt property be assessed at market value as of January 1st.",
    "assetClasses": [
      "multifamily",
      "office",
      "retail",
      "industrial",
      "land"
    ],
    "entities": [
      "county:ada"
    ],
    "topics": [
      "assessment",
      "property-taxes"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Ada County, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": null,
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Real & Manufactured Property Assessment — Ada County Assessor",
        "url": "https://adacounty.id.gov/assessor/property-assessments-records/real-manufactured-property-assessment/",
        "publisher": "Ada County Assessor",
        "tier": 1
      }
    ]
  },
  {
    "id": "boise-i3-purpose-and-buffer",
    "claim": "Boise's I-3 Industrial Technology district provides for manufacturing and technological facilities with greater impact than the mixed-use districts allow; the code states such land should be served by major transportation facilities and buffered from adjacent residential areas.",
    "quote": "The I-3 zoning district is intended to provide for manufacturing and technological facilities that may have a greater impact on the surrounding area than industries allowed in the mixed-use zoning districts. Lands in the I-3 zoning district should be served by major transportation facilities and be buffered from adjacent residential areas.",
    "assetClasses": [
      "industrial"
    ],
    "entities": [
      "city:boise-city"
    ],
    "topics": [
      "zoning",
      "industrial",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Boise, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": null,
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Industrial Technology (I-3) Zoning District — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/industrial-technology/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      }
    ]
  },
  {
    "id": "boise-i3-height-linked-setback",
    "claim": "Boise's I-3 district ties its front setback to building height — a minimum of 45 feet plus one additional foot for every foot of building height above 45 feet, or 100 feet — with the street side, interior side and rear yard following the front standard. The 100-foot alternative applies where the property is adjacent to a Residential zoning district or residential use. Where a development forms part of an adopted Industrial Technology master plan, the setbacks apply only to the perimeter of the campus.",
    "quote": "If a development is part of an adopted Industrial Technology master plan, setbacks shall apply only to the perimeter of the campus.",
    "assetClasses": [
      "industrial",
      "land"
    ],
    "entities": [
      "city:boise-city"
    ],
    "topics": [
      "zoning",
      "industrial",
      "land",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Boise, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": null,
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Boise City Code Tables 11-02.27, 11-02.29, 11-02.31 — I-1, I-2 and I-3 Lot and Building Standards",
        "url": "https://codelibrary.amlegal.com/codes/boise_id/latest/boise/0-0-0-65657",
        "publisher": "City of Boise (American Legal Publishing)",
        "tier": 1
      }
    ]
  },
  {
    "id": "boise-airport-influence-overlay",
    "claim": "Boise maintains an Airport Influence Area Overlay whose stated purposes include promoting development compatible with and protective of safe airport operation, and ensuring development is compatible with noise levels from airport operations.",
    "quote": "The purpose of the AI-O district is to: (a) Promote development that is compatible with and protects the safe operation of the airport; (b) Ensure all development is compatible with the noise levels from operations at the airport;",
    "assetClasses": [
      "industrial",
      "office",
      "retail",
      "land",
      "multifamily"
    ],
    "entities": [
      "city:boise-city"
    ],
    "topics": [
      "zoning",
      "industrial",
      "land",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Boise, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": null,
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Airport Influence Area Overlay (AI-O) — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/airport-influence-area-overlay/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      }
    ]
  },
  {
    "id": "boise-mx2-mixed-use-general",
    "claim": "Boise's MX-2 Mixed-Use General district provides for a mix of office, commercial, institutional and residential at a scale serving community needs broader than a nearby neighbourhood, with building height capped at 45 feet and front setbacks set as a range of minimum 0 to maximum 20 feet.",
    "quote": "The MX-2 district is intended to provide opportunities for a mix of office, commercial, institutional, and residential at a scale designed to serve community needs broader than those of nearby neighborhoods.",
    "assetClasses": [
      "office",
      "retail",
      "multifamily"
    ],
    "entities": [
      "city:boise-city"
    ],
    "topics": [
      "zoning",
      "office",
      "retail",
      "multifamily",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Boise, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": null,
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Mixed-Use General (MX-2) Zoning District — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/mixed-use-general/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      }
    ]
  },
  {
    "id": "boise-r3-no-maximum-density",
    "claim": "Boise's R-3 Residential Urban district states no maximum density. Its codified table gives a minimum lot area of 1,500 square feet for single-family attached and 2,000 square feet for all other uses, a 20-foot average lot width, a 20-foot minimum street frontage, and a density maximum of N/A.",
    "quote": "LOT STANDARDS [1] Lot Area (minimum) Single-Family Attached: 1,500 sf. All Other Uses: 2,000 sf. Lot Width (average) 20 ft. Street Frontage (minimum) 20 ft. Density (maximum) N/A",
    "assetClasses": [
      "multifamily",
      "land"
    ],
    "entities": [
      "city:boise-city"
    ],
    "topics": [
      "zoning",
      "multifamily",
      "land",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Boise, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": null,
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Boise City Code Table 11-02.11 — R-3 Lot and Building Standards",
        "url": "https://codelibrary.amlegal.com/codes/boise_id/latest/boise/0-0-0-65331",
        "publisher": "City of Boise (American Legal Publishing)",
        "tier": 1
      }
    ]
  },
  {
    "id": "ada-county-zoning-districts-schedule",
    "claim": "Ada County's adopted zoning ordinance establishes eighteen base districts and eight overlay districts. Its commercial and industrial base districts are Limited Office (LO), Neighborhood Commercial (C1), Community Commercial (C2), Light Industrial (M1), General Industrial (M2) and Airport Industrial (M3), alongside a Planned Community (PC) district and ten residential and rural districts.",
    "quote": "8-2-16: LIMITED OFFICE (LO) 8-2-17: NEIGHBORHOOD COMMERCIAL (C1) 8-2-18: COMMUNITY COMMERCIAL (C2) 8-2-19: LIGHT INDUSTRIAL (M1) 8-2-20: GENERAL INDUSTRIAL (M2) 8-2-21: AIRPORT INDUSTRIAL (M3) 8-2-22: PLANNED COMMUNITY (PC)",
    "assetClasses": [
      "industrial",
      "office",
      "retail",
      "land",
      "multifamily"
    ],
    "entities": [
      "county:ada",
      "area:unincorporated-ada"
    ],
    "topics": [
      "zoning",
      "industrial",
      "office",
      "retail",
      "land",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "unincorporated Ada County, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": null,
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Ada County Ordinance No. 1002 — repealing and re-enacting Ada County Code Title 8, the Ada County Zoning Ordinance",
        "url": "https://adacounty.id.gov/clerk/wp-content/uploads/sites/9/2025/11/1002.pdf",
        "publisher": "Ada County Clerk",
        "tier": 1
      }
    ]
  },
  {
    "id": "ada-county-vs-city-zoning-vocabularies-differ",
    "claim": "Ada County and the City of Boise use entirely different zoning vocabularies for the same kinds of property. The county's adopted code calls its industrial districts M1 Light Industrial, M2 General Industrial and M3 Airport Industrial; Boise calls its I-1 Light Industrial, I-2 Heavy Industrial and I-3 Industrial Technology. The county's commercial districts are LO, C1 and C2; Boise's equivalents sit in its mixed-use MX series. A parcel does not change character at a city limit, but the code governing it does.",
    "quote": "8-2-19: LIGHT INDUSTRIAL (M1) 8-2-20: GENERAL INDUSTRIAL (M2) 8-2-21: AIRPORT INDUSTRIAL (M3)",
    "assetClasses": [
      "industrial",
      "office",
      "retail",
      "land"
    ],
    "entities": [
      "county:ada",
      "city:boise-city",
      "area:unincorporated-ada"
    ],
    "topics": [
      "zoning",
      "jurisdiction",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Ada County, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": null,
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Ada County Ordinance No. 1002 — repealing and re-enacting Ada County Code Title 8, the Ada County Zoning Ordinance",
        "url": "https://adacounty.id.gov/clerk/wp-content/uploads/sites/9/2025/11/1002.pdf",
        "publisher": "Ada County Clerk",
        "tier": 1
      },
      {
        "title": "Industrial Light (I-1) Zoning District — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/industrial-light/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      },
      {
        "title": "Industrial Heavy (I-2) Zoning District — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/industrial-heavy/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      },
      {
        "title": "Industrial Technology (I-3) Zoning District — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/industrial-technology/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      }
    ]
  },
  {
    "id": "boise-mx5-no-height-maximum",
    "claim": "Boise's MX-5 Mixed-Use Downtown district states no maximum building height, where every other Boise district read so far carries one: MX-2 at 45 feet, R-3 at four stories not exceeding 50 feet, I-1 and I-2 at 55 feet, and I-3 at 150 feet.",
    "quote": "HEIGHT (MAXIMUM) D Building Height N/A",
    "assetClasses": [
      "office",
      "retail",
      "multifamily",
      "land"
    ],
    "entities": [
      "city:boise-city"
    ],
    "topics": [
      "zoning",
      "office",
      "retail",
      "multifamily",
      "land",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Boise, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": null,
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Mixed-Use Downtown (MX-5) Zoning District — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/mixed-use-downtown/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      },
      {
        "title": "Mixed-Use General (MX-2) Zoning District — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/mixed-use-general/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      },
      {
        "title": "Residential Urban (R-3) Zoning District — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/residential-urban/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      },
      {
        "title": "Industrial Light (I-1) Zoning District — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/industrial-light/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      },
      {
        "title": "Industrial Heavy (I-2) Zoning District — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/industrial-heavy/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      },
      {
        "title": "Industrial Technology (I-3) Zoning District — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/industrial-technology/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      }
    ]
  },
  {
    "id": "boise-mx5-downtown-purpose",
    "claim": "Boise's MX-5 district provides for a mix of higher-intensity office, commercial, institutional and residential uses, is intended to serve the Downtown Planning Area defined in the Comprehensive Plan, and sets front and side-street setbacks as a range of minimum 0 to maximum 20 feet with interior side and rear minimums of 0 feet.",
    "quote": "The MX-5 district is intended to provide opportunities for a mix of higher intensity office, commercial, institutional, and residential uses. The MX-5 district is intended to accommodate the needs of the city's Downtown Planning Area as defined in the Comprehensive Plan and to provide for activities conducive to a compact, concentrated, and walkable urban downtown mixed-use center.",
    "assetClasses": [
      "office",
      "retail",
      "multifamily"
    ],
    "entities": [
      "city:boise-city"
    ],
    "topics": [
      "zoning",
      "office",
      "retail",
      "multifamily",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Boise, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": null,
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Mixed-Use Downtown (MX-5) Zoning District — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/mixed-use-downtown/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      }
    ]
  },
  {
    "id": "boise-mx4-transit-oriented",
    "claim": "Boise's MX-4 district supports transit-oriented development concentrated at identified transit stations, and the city states the district will be expanded as new best-in-class transit routes are added and stations identified.",
    "quote": "The MX-4 district is intended to provide opportunities for a mix of office, commercial, institutional, and residential uses to support transit. This zoning district will require transit-oriented development concentrated at identified transit stations. This zoning district will be expanded as new investments in best-in-class transit routes are added and transit stations identified.",
    "assetClasses": [
      "office",
      "retail",
      "multifamily",
      "land"
    ],
    "entities": [
      "city:boise-city"
    ],
    "topics": [
      "zoning",
      "multifamily",
      "office",
      "land",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Boise, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": null,
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Mixed-Use Transit Oriented Development Node (MX-4) — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/mixed-use-transit-oriented-development-node/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      }
    ]
  },
  {
    "id": "boise-flood-protection-overlay-purpose",
    "claim": "Boise maintains a Flood Protection Overlay whose stated purpose recognises that the city's flood hazard areas are subject to periodic inundation, and that flood losses are caused both by natural forces and by construction practices that increase flood heights and velocities, and by structures inadequately anchored or flood-proofed.",
    "quote": "The flood hazard areas of Boise City are subject to periodic inundation, which may result in loss of life and property, health and safety hazards, disruption of commerce and government services, extraordinary public expenditures for flood protection and relief, and impairment of the tax base, all of which adversely affect the public health, safety, and general welfare.",
    "assetClasses": [
      "industrial",
      "office",
      "retail",
      "multifamily",
      "land"
    ],
    "entities": [
      "city:boise-city"
    ],
    "topics": [
      "flood",
      "zoning",
      "land"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Boise, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": null,
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Flood Protection Overlay — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/flood-protection-overlay/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      }
    ]
  },
  {
    "id": "gse-multifamily-more-than-four",
    "claim": "The federal housing-finance definition that produces the familiar 1-4 versus 5+ split is in FHFA regulation: multifamily housing means a residence consisting of more than four dwelling units, and single-family housing means a residence consisting of one to four dwelling units.",
    "quote": "Multifamily housing means a residence consisting of more than four dwelling units. … Single-family housing means a residence consisting of one to four dwelling units.",
    "assetClasses": [
      "multifamily"
    ],
    "entities": [
      "state:id"
    ],
    "topics": [
      "multifamily",
      "lending",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "United States (federal)",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "12 CFR § 1282.1 — Definitions (FHFA, Enterprise Housing Goals)",
        "url": "https://www.ecfr.gov/current/title-12/chapter-XII/subchapter-E/part-1282",
        "publisher": "Federal Housing Finance Agency / eCFR",
        "tier": 1
      }
    ]
  },
  {
    "id": "census-multifamily-starts-at-two",
    "claim": "The U.S. Census Bureau treats a two-unit structure as multifamily. Its Building Permits Survey tabulates one-unit structures, then 2 units, 3 and 4 units combined, and 5 or more units — so five is where Census stops disaggregating, not where multifamily begins. The American Community Survey uses brackets of 1 detached, 1 attached, 2, 3 or 4, 5 to 9, 10 to 19, 20 to 49, and 50 or more.",
    "quote": "Multifamily structures are classified by the number of housing units in the structure. Data are tabulated for 2 units, 3 and 4 units combined, and 5 or more unit structures.",
    "assetClasses": [
      "multifamily"
    ],
    "entities": [
      "state:id"
    ],
    "topics": [
      "multifamily",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "United States (federal)",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Building Permits Survey — Definitions",
        "url": "https://www.census.gov/construction/bps/definitions.html",
        "publisher": "U.S. Census Bureau",
        "tier": 1
      },
      {
        "title": "2023 American Community Survey Subject Definitions (Units in Structure, p. 44)",
        "url": "https://www2.census.gov/programs-surveys/acs/tech_docs/subject_definitions/2023_ACSSubjectDefinitions.pdf",
        "publisher": "U.S. Census Bureau",
        "tier": 1
      }
    ]
  },
  {
    "id": "hud-multifamily-not-uniform",
    "claim": "HUD has no single multifamily unit threshold. Its Section 207, 221(d)(4) and 223(f) programmes require five or more units, but Section 220 in urban renewal areas reaches two or more units and Section 231 rental housing for the elderly requires eight or more.",
    "quote": "Such property or project may include five or more family units and may include such commercial and community facilities as the Secretary deems adequate to serve the occupants.",
    "assetClasses": [
      "multifamily"
    ],
    "entities": [
      "state:id"
    ],
    "topics": [
      "multifamily",
      "lending",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "United States (federal)",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Descriptions of Multifamily Programs",
        "url": "https://www.hud.gov/hud-partners/multifamily-programs",
        "publisher": "U.S. Department of Housing and Urban Development",
        "tier": 1
      },
      {
        "title": "12 U.S.C. § 1713 — National Housing Act § 207, rental housing insurance",
        "url": "https://www.law.cornell.edu/uscode/text/12/1713",
        "publisher": "United States Code",
        "tier": 2
      }
    ]
  },
  {
    "id": "multifamily-threshold-varies-across-six-systems",
    "claim": "At least six systems draw the residential/multifamily line differently, and no two of them agree in scope: Ada County assessment routes properties above four units to commercial appraisers; Idaho's disclosure act covers one to four dwelling units; Idaho's domestic water statute excludes multiple-dwelling developments with no unit count at all; the Census treats two units as multifamily and uses five only as a tabulation bracket; FHFA defines multifamily as more than four dwelling units for housing finance; and HUD's own programmes use two, five or eight depending on the programme.",
    "quote": null,
    "assetClasses": [
      "multifamily"
    ],
    "entities": [
      "county:ada",
      "state:id"
    ],
    "topics": [
      "multifamily",
      "assessment",
      "disclosure",
      "water",
      "lending",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Ada County, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "12 CFR § 1282.1 — Definitions (FHFA, Enterprise Housing Goals)",
        "url": "https://www.ecfr.gov/current/title-12/chapter-XII/subchapter-E/part-1282",
        "publisher": "Federal Housing Finance Agency / eCFR",
        "tier": 1
      },
      {
        "title": "Building Permits Survey — Definitions",
        "url": "https://www.census.gov/construction/bps/definitions.html",
        "publisher": "U.S. Census Bureau",
        "tier": 1
      },
      {
        "title": "Descriptions of Multifamily Programs",
        "url": "https://www.hud.gov/hud-partners/multifamily-programs",
        "publisher": "U.S. Department of Housing and Urban Development",
        "tier": 1
      },
      {
        "title": "Real & Manufactured Property Assessment — Ada County Assessor",
        "url": "https://adacounty.id.gov/assessor/property-assessments-records/real-manufactured-property-assessment/",
        "publisher": "Ada County Assessor",
        "tier": 1
      },
      {
        "title": "Idaho Code § 55-2504 — Property condition disclosure required",
        "url": "https://legislature.idaho.gov/statutesrules/idstat/title55/t55ch25/sect55-2504/",
        "publisher": "Idaho State Legislature",
        "tier": 1
      },
      {
        "title": "Idaho Code § 42-111 — Domestic purposes defined",
        "url": "https://legislature.idaho.gov/statutesrules/idstat/title42/t42ch1/sect42-111/",
        "publisher": "Idaho State Legislature",
        "tier": 1
      }
    ]
  },
  {
    "id": "boise-r3-height",
    "claim": "Boise's R-3 Residential Urban district caps building height at four stories not to exceed 50 feet.",
    "quote": "HEIGHT (MAXIMUM) D Building Height 4 stories not to exceed 50 ft.",
    "assetClasses": [
      "multifamily",
      "land"
    ],
    "entities": [
      "city:boise-city"
    ],
    "topics": [
      "zoning",
      "multifamily",
      "land",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Boise, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Residential Urban (R-3) Zoning District — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/residential-urban/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      }
    ]
  },
  {
    "id": "boise-district-pages-omit-footnote-definitions",
    "claim": "The City of Boise's online zoning district pages reproduce each district's dimensional standards table together with its bracketed footnote markers, but do not publish the footnote definitions those markers point to. As accessed on 10 September 2026, the R-3 table carried markers [1] through [5], the I-3 table carried [1] through [3], and the I-1 and I-2 tables carried [1], and no definition for any of them appeared on any of those pages.",
    "quote": "LOT STANDARDS [1] Lot Area (minimum) [2] Single-Family Attached: 1,500 sf. All Other Uses: 2,00 sf. Lot Width (average) 20 ft. Street Frontage (minimum) 20 ft. Density (maximum) [2][3] N./A",
    "assetClasses": [
      "industrial",
      "office",
      "retail",
      "multifamily",
      "land"
    ],
    "entities": [
      "city:boise-city"
    ],
    "topics": [
      "zoning",
      "research-method",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Boise, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": "VOLATILE",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Residential Urban (R-3) Zoning District — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/residential-urban/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      },
      {
        "title": "Industrial Light (I-1) Zoning District — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/industrial-light/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      },
      {
        "title": "Industrial Heavy (I-2) Zoning District — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/industrial-heavy/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      },
      {
        "title": "Industrial Technology (I-3) Zoning District — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/industrial-technology/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      }
    ]
  },
  {
    "id": "boise-i1-i2-zero-interior-rear-setbacks",
    "claim": "Boise's I-1 and I-2 industrial tables set minimum interior side and rear yard setbacks at zero feet, but only away from housing. Where the property is adjacent to a Residential zoning district or a residential use, the minimum becomes 30 feet for development under three acres, 50 feet between three and ten acres, and 100 feet for development of ten or more acres. Front is 20 feet and street side 15 feet in both districts.",
    "quote": "When adjacent to a Residential zoning district or residential use, 30 ft. minimum for all development under three acres, 50 ft. minimum for all development between three acres and 10 acres, and 100 ft. minimum for all development of 10 or more acres.",
    "assetClasses": [
      "industrial"
    ],
    "entities": [
      "city:boise-city"
    ],
    "topics": [
      "zoning",
      "industrial",
      "land",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Boise, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Boise City Code Tables 11-02.27, 11-02.29, 11-02.31 — I-1, I-2 and I-3 Lot and Building Standards",
        "url": "https://codelibrary.amlegal.com/codes/boise_id/latest/boise/0-0-0-65657",
        "publisher": "City of Boise (American Legal Publishing)",
        "tier": 1
      }
    ]
  },
  {
    "id": "idaho-assessment-ratio-band-90-110",
    "claim": "Idaho law does not require an assessment to match market value exactly. It requires that the median ratio of assessed value to market value, for each category of property tested, fall within a range of 90 percent to 110 percent of market value, tested with statistical methods, and that categories be within five percentage points of one another.",
    "quote": "The recognized appraisal methods shall, at a minimum, require the assessment of such property to reflect, within reasonable statistical certainty, the median ratio of assessed value to market value for the categories of property being tested within a range of ninety percent (90%) to one hundred ten percent (110%) of market value",
    "assetClasses": [
      "industrial",
      "office",
      "retail",
      "multifamily",
      "land"
    ],
    "entities": [
      "county:ada"
    ],
    "topics": [
      "assessment",
      "valuation",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Idaho Code § 63-208 — Rules pertaining to market value — Duty of assessors",
        "url": "https://legislature.idaho.gov/statutesrules/idstat/Title63/T63CH2/SECT63-208/",
        "publisher": "Idaho State Legislature",
        "tier": 1
      }
    ]
  },
  {
    "id": "idaho-appraisal-cycle-five-years",
    "claim": "Idaho requires every taxable property to be appraised at least once every five years, on a rolling schedule reaching fifteen percent of a county's properties in year one and one hundred percent by year five. In the years between appraisals, a property is indexed to current market value using market value property transactions rather than individually appraised.",
    "quote": "Annually, all taxable property, not appraised that year, shall be indexed to reflect current market value for assessment purposes using market value property transactions and results of the annual appraisal of taxable property.",
    "assetClasses": [
      "industrial",
      "office",
      "retail",
      "multifamily",
      "land"
    ],
    "entities": [
      "county:ada"
    ],
    "topics": [
      "assessment",
      "valuation",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Idaho Code § 63-314 — County valuation program to be carried on by assessor",
        "url": "https://legislature.idaho.gov/statutesrules/idstat/Title63/T63CH3/SECT63-314/",
        "publisher": "Idaho State Legislature",
        "tier": 1
      }
    ]
  },
  {
    "id": "idaho-assessment-lien-date-statutory",
    "claim": "Idaho sets the assessment date by statute at 12:01 a.m. on the first day of January of the year the taxes are levied, for all real, personal and operating property subject to property taxation.",
    "quote": "All real, personal and operating property subject to property taxation must be assessed annually at market value for assessment purposes as of 12:01 a.m. of the first day of January in the year in which such property taxes are levied, except as otherwise provided.",
    "assetClasses": [
      "industrial",
      "office",
      "retail",
      "multifamily",
      "land"
    ],
    "entities": [
      "county:ada"
    ],
    "topics": [
      "assessment",
      "property-taxes",
      "valuation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": "EVERGREEN",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Idaho Code § 63-205 — Assessment — Market value for assessment purposes",
        "url": "https://legislature.idaho.gov/statutesrules/idstat/Title63/T63CH2/SECT63-205/",
        "publisher": "Idaho State Legislature",
        "tier": 1
      }
    ]
  },
  {
    "id": "ada-county-commercial-districts-tied-to-areas-of-impact",
    "claim": "Every commercial and industrial district in Ada County's adopted zoning ordinance carries the same stated purpose: to encourage those uses primarily inside areas of impact, implementing the comprehensive plans adopted as part of the area of impact agreements, and to be established outside an area of impact only on a limited basis. The district's allowed uses turn on the availability of urban public facilities and the applicable comprehensive plan designation.",
    "quote": "The General Industrial (M2) District promotes the public health, safety, and welfare of Ada County by encouraging industrial uses primarily inside areas of impact to implement the applicable comprehensive plans that are adopted as part of the area of impact agreements. The General Industrial (M2) District may also be established outside areas of impact on a limited basis.",
    "assetClasses": [
      "industrial",
      "office",
      "retail",
      "land"
    ],
    "entities": [
      "county:ada"
    ],
    "topics": [
      "zoning",
      "jurisdiction",
      "industrial",
      "office",
      "retail",
      "land",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Ada County, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Ada County Ordinance No. 1002 — repealing and re-enacting Ada County Code Title 8, the Ada County Zoning Ordinance",
        "url": "https://adacounty.id.gov/clerk/wp-content/uploads/sites/9/2025/11/1002.pdf",
        "publisher": "Ada County Clerk",
        "tier": 1
      }
    ]
  },
  {
    "id": "idaho-recorded-documents-are-public",
    "claim": "Idaho county recorder records are fully open. Every book of record, map, chart, survey and other paper on file must be open during office hours to any person who wishes to inspect it, without charge.",
    "quote": "All books of record, maps, charts, surveys and other papers on file in the recorder's office, must, during office hours, be open for the inspection of any person who may desire to inspect them, and may be inspected without charge",
    "assetClasses": [
      "industrial",
      "office",
      "retail",
      "multifamily",
      "land"
    ],
    "entities": [
      "county:ada"
    ],
    "topics": [
      "disclosure",
      "valuation",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Idaho Code § 31-2419 — Records open to inspection",
        "url": "https://legislature.idaho.gov/statutesrules/idstat/Title31/T31CH24/SECT31-2419/",
        "publisher": "Idaho State Legislature",
        "tier": 1
      }
    ]
  },
  {
    "id": "idaho-deed-content-requirement-omits-price",
    "claim": "Idaho states what a conveyance of real property must contain: a written instrument, subscribed by the party disposing of the property or an authorised agent, and the grantee's name and complete mailing address. The price is not among the required elements.",
    "quote": "A conveyance of an estate in real property may be made by an instrument in writing, subscribed by the party disposing of the same, or by his agent thereunto authorized by writing. The name of the grantee and his complete mailing address must appear on such instrument.",
    "assetClasses": [
      "industrial",
      "office",
      "retail",
      "multifamily",
      "land"
    ],
    "entities": [
      "county:ada"
    ],
    "topics": [
      "disclosure",
      "valuation",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Idaho Code § 55-601 — Conveyance — how made",
        "url": "https://legislature.idaho.gov/statutesrules/idstat/Title55/T55CH6/SECT55-601/",
        "publisher": "Idaho State Legislature",
        "tier": 1
      }
    ]
  },
  {
    "id": "idaho-is-a-non-disclosure-state",
    "claim": "Idaho is a non-disclosure state. County assessors say so in their own words and describe the consequence: they depend on the public to volunteer sales information when property changes hands, because no law requires it to be reported.",
    "quote": "Since Idaho is a non-disclosure state, the Assessor's office depends heavily on the public to provide sales and cost information.",
    "assetClasses": [
      "industrial",
      "office",
      "retail",
      "multifamily",
      "land"
    ],
    "entities": [
      "county:ada"
    ],
    "topics": [
      "disclosure",
      "valuation",
      "assessment",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Property Assessments and Records",
        "url": "https://www.bonnercountyid.gov/departments/Assessor/PROPERTYASSESSMENTSRECORDS",
        "publisher": "Bonner County Assessor",
        "tier": 2
      },
      {
        "title": "Assessor FAQ",
        "url": "https://www.canyoncounty.id.gov/elected-officials/assessor/assessor-faq/",
        "publisher": "Canyon County Assessor",
        "tier": 2
      }
    ]
  },
  {
    "id": "idaho-assessor-records-conditional-confidentiality",
    "claim": "Idaho exempts certain assessor records from public disclosure, including confidential commercial or financial information, but the exemption is not automatic: the taxpayer must claim it by stamping or marking the documents. The information that is always disclosable includes the owner's name and mailing address, the parcel number, the legal description, square footage and acreage, the assessed value, the tax district and rate, and the total property tax.",
    "quote": "it shall be the responsibility of the taxpayer to give notice of its claim to exemption by stamping or marking each page or the first page of each portion of documents so claimed",
    "assetClasses": [
      "industrial",
      "office",
      "retail",
      "multifamily",
      "land"
    ],
    "entities": [
      "county:ada"
    ],
    "topics": [
      "disclosure",
      "assessment",
      "valuation"
    ],
    "confidence": "MEDIUM",
    "jurisdiction": "Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Idaho Code § 74-107 — Records exempt from disclosure — Trade secrets, personal records, personnel records, and other records",
        "url": "https://legislature.idaho.gov/statutesrules/idstat/Title74/T74CH1/SECT74-107/",
        "publisher": "Idaho State Legislature",
        "tier": 1
      }
    ]
  },
  {
    "id": "noi-definition-freddie-mac",
    "claim": "Net operating income is the income from a property's operations available for repayment of debt and return on equity to the owner, after deducting economic vacancy and all expenses, excluding debt service.",
    "quote": "Net Operating Income is the income from a property's operations available for repayment of debt and return on equity to the owner after deducting economic vacancy and all expenses (exclusive of debt service).",
    "assetClasses": [
      "multifamily",
      "office",
      "retail",
      "industrial"
    ],
    "entities": [],
    "topics": [
      "valuation",
      "multifamily",
      "lending",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "United States",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Multifamily Seller/Servicer Guide — Glossary",
        "url": "https://mf.freddiemac.com/docs/mf_guide_glossary.pdf",
        "publisher": "Freddie Mac",
        "tier": 2
      }
    ]
  },
  {
    "id": "cap-rate-definition-freddie-mac",
    "claim": "A capitalization rate is the percentage rate representing the relationship between the value of a property and the net operating income it produces.",
    "quote": "The Capitalization Rate is the percentage rate that represents the proper relationship between the value of the Property and the Net Operating Income that the Property produces.",
    "assetClasses": [
      "multifamily",
      "office",
      "retail",
      "industrial"
    ],
    "entities": [],
    "topics": [
      "valuation",
      "multifamily",
      "lending",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "United States",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Multifamily Seller/Servicer Guide — Glossary",
        "url": "https://mf.freddiemac.com/docs/mf_guide_glossary.pdf",
        "publisher": "Freddie Mac",
        "tier": 2
      }
    ]
  },
  {
    "id": "idaho-architect-exemption-ends-at-three-units",
    "claim": "Idaho's architects chapter does not apply to architectural services for a building used as a single or multiple family residence not exceeding three units or three stories in height. The exemption stops at three units, so a fourplex sits above it and a triplex does not — a boundary at three, in a state where other systems draw the line at two, four or five.",
    "quote": "The rendering of any architectural service required in the erection, enlargement, alteration or repair of any building, where the building is to be or is used as a single or multiple family residence not exceeding three (3) units or three (3) stories in height",
    "assetClasses": [
      "multifamily"
    ],
    "entities": [],
    "topics": [
      "multifamily",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Idaho Code § 54-306 — Exemptions [from the Architects chapter]",
        "url": "https://legislature.idaho.gov/statutesrules/idstat/Title54/T54CH3/SECT54-306/",
        "publisher": "Idaho State Legislature",
        "tier": 1
      }
    ]
  },
  {
    "id": "boise-city-pages-differ-from-codified-tables",
    "claim": "The City of Boise's zoning district webpages are summaries and differ from the codified ordinance in ways that matter. They reproduce the dimensional tables and their bracketed markers but publish no footnote definitions, so the I-1 page shows an interior side setback of \"0 ft. [1]\" and the I-3 page a building height of \"150 ft. [3]\" without the qualifications those markers point to. In the R-3 table the markers sit on different rows than the code places them, and the minimum lot area for all other uses is printed as \"2,00 sf\" where the code reads 2,000 square feet.",
    "quote": "Lot Width (average) 20 ft. Street Frontage (minimum) 20 ft. Density (maximum) N/A",
    "assetClasses": [
      "industrial",
      "office",
      "retail",
      "multifamily",
      "land"
    ],
    "entities": [
      "city:boise-city"
    ],
    "topics": [
      "zoning",
      "research-method",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Boise, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": "VOLATILE",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Boise City Code Table 11-02.11 — R-3 Lot and Building Standards",
        "url": "https://codelibrary.amlegal.com/codes/boise_id/latest/boise/0-0-0-65331",
        "publisher": "City of Boise (American Legal Publishing)",
        "tier": 1
      },
      {
        "title": "Residential Urban (R-3) Zoning District — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/residential-urban/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      },
      {
        "title": "Industrial Light (I-1) Zoning District — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/industrial-light/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      },
      {
        "title": "Industrial Technology (I-3) Zoning District — City of Boise",
        "url": "https://www.cityofboise.org/departments/planning-and-development-services/planning/zoning/zoning-districts/industrial-technology/",
        "publisher": "City of Boise Planning and Development Services",
        "tier": 1
      }
    ]
  },
  {
    "id": "treasure-valley-setback-governed-by-residential-adjacency",
    "claim": "Across the Treasure Valley, the setback that actually governs a commercial or industrial parcel is usually the one measured against housing — and no two cities express it the same way. Boise's I-1 and I-2 print a zero-foot interior side and rear yard that becomes 30, 50 or 100 feet next to a residential district or use depending on the size of the development. Star requires a minimum of 15 feet in its CBD, C-1, C-2, LO, IL, PS, RC and M-U zones when adjacent to a residential use or zone. Kuna does something different again: the setback becomes whatever the adjacent residential district itself requires.",
    "quote": "When a commercial and/or industrial use abuts a residential zoning district, the yard setback requirements shall be the same as required in the adjacent residential district. When residents are located in commercial or industrial zones, the yard setbacks are the same as required for the R-4 residential zoning district.",
    "assetClasses": [
      "industrial",
      "office",
      "retail",
      "land"
    ],
    "entities": [
      "city:boise-city",
      "city:star",
      "city:kuna"
    ],
    "topics": [
      "zoning",
      "industrial",
      "land",
      "jurisdiction",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Treasure Valley, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Kuna City Code § 5-8-504 — Schedule of Area and Structure Requirements",
        "url": "https://api.municode.com/CodesContent?productId=14925&jobId=492823&nodeId=TIT5KUDERECO_CH8ZOCO_PT5ZODI_5-8-504SCHEARST&groupChunks=false",
        "publisher": "City of Kuna, Idaho",
        "tier": 1
      },
      {
        "title": "Star City Code Table 8-3A-4 — Zoning District Dimensional Standards",
        "url": "https://api.municode.com/CodesContent?productId=17396&jobId=488846&nodeId=TIT8UNDECO_CH3ZODIST_ARTADIES_8-3A-4ZODIDIST&groupChunks=false",
        "publisher": "City of Star, Idaho",
        "tier": 1
      },
      {
        "title": "Boise City Code Tables 11-02.27, 11-02.29, 11-02.31 — I-1, I-2 and I-3 Lot and Building Standards",
        "url": "https://codelibrary.amlegal.com/codes/boise_id/latest/boise/0-0-0-65657",
        "publisher": "City of Boise (American Legal Publishing)",
        "tier": 1
      }
    ]
  },
  {
    "id": "star-light-industry-300ft-residential-separation",
    "claim": "Star's Light Industrial district requires all mechanical equipment emissions, shipping and delivery, and other outdoor activity areas to sit at least three hundred feet from any abutting residential district, or the use becomes subject to a conditional use permit.",
    "quote": "All mechanical equipment emissions; shipping and/or delivery; or other outdoor activity areas shall be located a minimum of three hundred feet (300') from any abutting residential districts, or the use is subject to a conditional use permit.",
    "assetClasses": [
      "industrial",
      "land"
    ],
    "entities": [
      "city:star"
    ],
    "topics": [
      "zoning",
      "industrial",
      "land",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Star, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Star City Code § 8-3D-1 — LI Light Industrial District",
        "url": "https://api.municode.com/CodesContent?productId=17396&jobId=488846&nodeId=TIT8UNDECO_CH3ZODIST_ARTDADLIINDIST_8-3D-1LILIINDI&groupChunks=false",
        "publisher": "City of Star, Idaho",
        "tier": 1
      }
    ]
  },
  {
    "id": "garden-city-c2-is-mixed-use-not-commercial",
    "claim": "Garden City's C-2 is a mixed use commercial district, not a general commercial one. That inverts the convention in neighbouring cities, where C-2 denotes a commercial district — Star and Kuna both use C-2 for commercial and place mixed use elsewhere. Garden City's only industrial district is LI Light Industrial, with a 55-foot height maximum, while the height cell for its C-1 and C-2 districts is left blank in the table.",
    "quote": "Mixed use commercial (C-2)",
    "assetClasses": [
      "industrial",
      "office",
      "retail",
      "multifamily",
      "land"
    ],
    "entities": [
      "city:garden-city"
    ],
    "topics": [
      "zoning",
      "jurisdiction",
      "office",
      "retail",
      "differentiation"
    ],
    "confidence": "MEDIUM",
    "jurisdiction": "Garden City, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Garden City Code Title 8 Development Code, Article 8-2B — Nonresidential and Mixed Use Districts",
        "url": "https://ecode360.com/47141205",
        "publisher": "Garden City, Idaho",
        "tier": 1
      },
      {
        "title": "Star City Code Table 8-3A-4 — Zoning District Dimensional Standards",
        "url": "https://api.municode.com/CodesContent?productId=17396&jobId=488846&nodeId=TIT8UNDECO_CH3ZODIST_ARTADIES_8-3A-4ZODIDIST&groupChunks=false",
        "publisher": "City of Star, Idaho",
        "tier": 1
      },
      {
        "title": "Kuna City Code § 5-8-504 — Schedule of Area and Structure Requirements",
        "url": "https://api.municode.com/CodesContent?productId=14925&jobId=492823&nodeId=TIT5KUDERECO_CH8ZOCO_PT5ZODI_5-8-504SCHEARST&groupChunks=false",
        "publisher": "City of Kuna, Idaho",
        "tier": 1
      }
    ]
  },
  {
    "id": "eagle-multistory-side-setback-increment",
    "claim": "Eagle expands its side setback with building storeys rather than with proximity to housing. Except for single-family attached dwellings, a multi-storey structure requires an additional five feet of side setback per storey, in every district including its M-1, BP, M-2 and M-3 industrial districts, whose tables otherwise show a zero-foot interior side. Eagle also requires residential buildings located in non-residential districts to meet the residential height and area regulations.",
    "quote": "Except for single-family attached dwellings, an additional 5 feet per story side setback is required for multi-story structures. Height not to exceed maximum allowed within the zone.",
    "assetClasses": [
      "industrial",
      "office",
      "retail",
      "land"
    ],
    "entities": [
      "city:eagle"
    ],
    "topics": [
      "zoning",
      "industrial",
      "land",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Eagle, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Eagle City Code § 8-2-4 — Schedule of Building Height and Lot Area Regulations",
        "url": "https://codelibrary.amlegal.com/codes/eagleid/latest/eagle_id/0-0-0-9941",
        "publisher": "City of Eagle, Idaho",
        "tier": 1
      }
    ]
  },
  {
    "id": "meridian-industrial-table-defers-to-exceptions",
    "claim": "Meridian sets a single set of dimensional standards for both of its industrial districts, I-L and I-H: front, rear and interior side setbacks of zero feet, a street setback of 35 feet, and a maximum building height of 50 feet. The table does not present those figures as final — its own text directs the reader to exceptions and clarifications set out elsewhere in the code.",
    "quote": "Table 11-2C-3 of this subsection shall be used for determining required setbacks, street and use landscape buffers and maximum building height standards for development in each of the industrial districts. Subsection (A)(2) of this section and subsection 11-3B-7.C.1.c of this title sets forth certain exceptions and additional clarification for the dimensional standards.",
    "assetClasses": [
      "industrial",
      "land"
    ],
    "entities": [
      "city:meridian"
    ],
    "topics": [
      "zoning",
      "industrial",
      "land",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Meridian, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Meridian Unified Development Code Table 11-2C-3 — Dimensional Standards in the Industrial Districts",
        "url": "https://api.municode.com/CodesContent?productId=17170&jobId=490886&nodeId=TIT11UNDECO_CH2DIRE_ARTCINDI_11-2C-3ST&groupChunks=false",
        "publisher": "City of Meridian, Idaho",
        "tier": 1
      }
    ]
  },
  {
    "id": "m3-means-three-different-things-in-ada-county",
    "claim": "The designation M-3 does not mean one thing across the Treasure Valley. In unincorporated Ada County it is Airport Industrial, a live district in the adopted zoning ordinance. In Eagle it is Extractive Industrial, for the mining, processing and storage of mineral resources. In Kuna it was limited to mining uses and has been consolidated into M-2, so it no longer operates. Boise has no M-3 at all — its third industrial district is I-3 Industrial Technology, for technology and research uses.",
    "quote": "M-3 EXTRACTIVE INDUSTRIAL DISTRICT: To provide land for the mining, processing and storage of mineral resources.",
    "assetClasses": [
      "industrial",
      "land"
    ],
    "entities": [
      "county:ada",
      "city:kuna",
      "city:boise-city",
      "city:eagle"
    ],
    "topics": [
      "zoning",
      "jurisdiction",
      "industrial",
      "land",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Ada County, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Eagle City Code § 8-2-1 — Zoning Districts and Purposes",
        "url": "https://codelibrary.amlegal.com/codes/eagleid/latest/eagle_id/0-0-0-9941",
        "publisher": "City of Eagle, Idaho",
        "tier": 1
      },
      {
        "title": "Kuna City Code § 5-8-501 — Zoning Districts Established; Purpose",
        "url": "https://api.municode.com/CodesContent?productId=14925&jobId=492823&nodeId=TIT5KUDERECO_CH8ZOCO_PT5ZODI_5-8-501ZODIESPU&groupChunks=false",
        "publisher": "City of Kuna, Idaho",
        "tier": 1
      },
      {
        "title": "Ada County Ordinance No. 1002 — repealing and re-enacting Ada County Code Title 8, the Ada County Zoning Ordinance",
        "url": "https://adacounty.id.gov/clerk/wp-content/uploads/sites/9/2025/11/1002.pdf",
        "publisher": "Ada County Clerk",
        "tier": 1
      },
      {
        "title": "Boise City Code Tables 11-02.27, 11-02.29, 11-02.31 — I-1, I-2 and I-3 Lot and Building Standards",
        "url": "https://codelibrary.amlegal.com/codes/boise_id/latest/boise/0-0-0-65657",
        "publisher": "City of Boise (American Legal Publishing)",
        "tier": 1
      }
    ]
  },
  {
    "id": "star-residential-adjacency-floor-is-waivable",
    "claim": "Star's 15-foot minimum setback next to a residential use or zone is not absolute. The same footnote allows a waiver to be requested where the adjacent property has the potential to redevelop as a non-residential use in the future.",
    "quote": "A waiver may be requested if thee adjacent property has the potential to redevelop as a non-residential use in the future.",
    "assetClasses": [
      "industrial",
      "office",
      "retail",
      "land"
    ],
    "entities": [
      "city:star"
    ],
    "topics": [
      "zoning",
      "industrial",
      "land",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Star, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Star City Code Table 8-3A-4 — Zoning District Dimensional Standards",
        "url": "https://api.municode.com/CodesContent?productId=17396&jobId=488846&nodeId=TIT8UNDECO_CH3ZODIST_ARTADIES_8-3A-4ZODIDIST&groupChunks=false",
        "publisher": "City of Star, Idaho",
        "tier": 1
      }
    ]
  },
  {
    "id": "meridian-specific-area-plans-displace-the-table",
    "claim": "Meridian's own dimensional table says it can be overridden. Setback, landscape buffer, building height and parking standards within an adopted specific area plan take precedence over the standards in the table. Where an adjacent property is vacant, the Director determines its designation from the Comprehensive Plan, so even the input to a buffer requirement can be a matter of judgement rather than a fact on the ground.",
    "quote": "Dimensional standards for setbacks, landscape buffers, building heights, and parking requirements within adopted specific area plans take precedence over standards provided in this table.",
    "assetClasses": [
      "industrial",
      "office",
      "retail",
      "multifamily",
      "land"
    ],
    "entities": [
      "city:meridian"
    ],
    "topics": [
      "zoning",
      "land",
      "jurisdiction",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Meridian, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Meridian Unified Development Code Table 11-2C-3 — Dimensional Standards in the Industrial Districts",
        "url": "https://api.municode.com/CodesContent?productId=17170&jobId=490886&nodeId=TIT11UNDECO_CH2DIRE_ARTCINDI_11-2C-3ST&groupChunks=false",
        "publisher": "City of Meridian, Idaho",
        "tier": 1
      }
    ]
  },
  {
    "id": "meridian-commercial-height-spans-six-districts",
    "claim": "Meridian's six commercial districts do not share a height standard. Maximum building height runs 35 feet in C-N Neighborhood Business and L-O Limited Office, 50 feet in C-C Community Business, 65 feet in C-G General Retail and Service Commercial and in M-E Mixed Employment, and 95 feet in H-E High Density Employment — a range of nearly three to one across districts a seller would think of as simply commercial.",
    "quote": "Maximum building height (in feet) 35 50 65 35 65 95",
    "assetClasses": [
      "office",
      "retail"
    ],
    "entities": [
      "city:meridian"
    ],
    "topics": [
      "zoning",
      "office",
      "retail",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Meridian, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Meridian Unified Development Code Table 11-2B-3 — Dimensional Standards in the Commercial Districts",
        "url": "https://api.municode.com/CodesContent?productId=17170&jobId=490886&nodeId=TIT11UNDECO_CH2DIRE_ARTBCODI_11-2B-3ST&groupChunks=false",
        "publisher": "City of Meridian, Idaho",
        "tier": 1
      }
    ]
  },
  {
    "id": "meridian-street-buffer-scales-with-road-class",
    "claim": "Meridian's commercial districts carry a street landscape buffer that scales with the classification of the road a property fronts, not with the district: 10 feet on a local street, 20 on a collector, 25 on an arterial, 35 on an entryway corridor and 50 along the interstate. A separate landscape buffer applies to adjacent residential uses, at 20 to 25 feet depending on the district.",
    "quote": "Street landscape buffer (in feet): Local 10 Collector 20 Arterial 25 Entryway corridor 35 Interstate 50",
    "assetClasses": [
      "office",
      "retail",
      "land"
    ],
    "entities": [
      "city:meridian"
    ],
    "topics": [
      "zoning",
      "office",
      "retail",
      "access",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Meridian, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Meridian Unified Development Code Table 11-2B-3 — Dimensional Standards in the Commercial Districts",
        "url": "https://api.municode.com/CodesContent?productId=17170&jobId=490886&nodeId=TIT11UNDECO_CH2DIRE_ARTBCODI_11-2B-3ST&groupChunks=false",
        "publisher": "City of Meridian, Idaho",
        "tier": 1
      }
    ]
  },
  {
    "id": "commercial-district-letters-do-not-correspond",
    "claim": "Commercial district letters do not correspond across Treasure Valley cities, in either direction. Eagle's C-2 is General Business, for commercial uses more intensive than those permitted in its other commercial zones; Garden City's C-2 is a mixed use commercial district; Star and Kuna both use C-2 for a commercial district of their own definition. The same idea also travels under different letters: a neighbourhood-scale business district is C-1 in Eagle and C-N in Meridian. Meridian's commercial set is C-N, C-C, C-G, L-O, M-E and H-E; Eagle's is L-O, C-1, C-2, C-3 and CBD.",
    "quote": "C-2 GENERAL BUSINESS DISTRICT: To permit the establishment of areas for commercial uses allowed in other commercial zones and commercial uses which are more intensive than those permitted in other commercial zones.",
    "assetClasses": [
      "office",
      "retail"
    ],
    "entities": [
      "city:eagle",
      "city:garden-city",
      "city:meridian"
    ],
    "topics": [
      "zoning",
      "jurisdiction",
      "office",
      "retail",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Treasure Valley, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Eagle City Code § 8-2-1 — Zoning Districts and Purposes",
        "url": "https://codelibrary.amlegal.com/codes/eagleid/latest/eagle_id/0-0-0-9941",
        "publisher": "City of Eagle, Idaho",
        "tier": 1
      },
      {
        "title": "Garden City Code Title 8 Development Code, Article 8-2B — Nonresidential and Mixed Use Districts",
        "url": "https://ecode360.com/47141205",
        "publisher": "Garden City, Idaho",
        "tier": 1
      },
      {
        "title": "Meridian Unified Development Code Table 11-2B-3 — Dimensional Standards in the Commercial Districts",
        "url": "https://api.municode.com/CodesContent?productId=17170&jobId=490886&nodeId=TIT11UNDECO_CH2DIRE_ARTBCODI_11-2B-3ST&groupChunks=false",
        "publisher": "City of Meridian, Idaho",
        "tier": 1
      }
    ]
  },
  {
    "id": "eagle-limited-office-purpose",
    "claim": "Eagle's L-O Limited Office district exists for groupings of professional, research, executive, administrative, accounting, clerical, stenographic, limited commercial and similar uses, and specifies that development shall not be traffic intensive.",
    "quote": "L-O LIMITED OFFICE DISTRICT: To permit the establishment of groupings of professional, research, executive, administrative, accounting, clerical, stenographic, limited commercial and similar uses.",
    "assetClasses": [
      "office"
    ],
    "entities": [
      "city:eagle"
    ],
    "topics": [
      "zoning",
      "office",
      "differentiation"
    ],
    "confidence": "HIGH",
    "jurisdiction": "Eagle, Idaho",
    "verifiedOn": "2026-09-10",
    "freshness": "SLOW-CHANGING",
    "temporalStatus": "CURRENT",
    "sources": [
      {
        "title": "Eagle City Code § 8-2-1 — Zoning Districts and Purposes",
        "url": "https://codelibrary.amlegal.com/codes/eagleid/latest/eagle_id/0-0-0-9941",
        "publisher": "City of Eagle, Idaho",
        "tier": 1
      }
    ]
  }
];

const byId = new Map(commercialClaims.map((c) => [c.id, c]));

export function commercialClaim(id: string): CommercialClaim | undefined {
  return byId.get(id);
}

/** Every claim naming this asset class. Includes shared, cross-class material. */
export function claimsForAssetClass(assetClass: string): CommercialClaim[] {
  return commercialClaims.filter((c) => c.assetClasses.includes(assetClass));
}

/**
 * Claims that DIFFERENTIATE an asset class — those naming it and carrying its
 * own topic. A claim true of every commercial building is real evidence but it
 * cannot distinguish one asset page from another, which is the whole test a
 * page has to pass before it may be indexed.
 */
export function claimsUniqueToAssetClass(assetClass: string): CommercialClaim[] {
  return commercialClaims.filter(
    (c) => c.assetClasses.includes(assetClass) && c.topics.includes(assetClass),
  );
}

export function commercialClaimsByTopic(topic: string): CommercialClaim[] {
  return commercialClaims.filter((c) => c.topics.includes(topic));
}
