// GENERATED by scripts/codegen/build-geography.mjs — DO NOT EDIT.
// Regenerate: node scripts/codegen/build-geography.mjs
//
// County membership derives from the Census place-to-county crosswalk via the
// entity registry, never from geometry. Build verdicts derive from how many
// approved claims are UNIQUE to a place — a page that cannot say anything its
// neighbours cannot say does not get indexed.

export type PlaceType = "CITY" | "CENSUS_DESIGNATED_PLACE";
export type BuildVerdict = "BUILD" | "RENDER_NOINDEX" | "DO_NOT_BUILD";

export interface Place {
  id: string;
  /** Common name, e.g. "Boise". */
  name: string;
  /** Census place name, which can differ, e.g. "Boise City". */
  censusPlaceName: string;
  slug: string;
  placeType: PlaceType;
  counties: string[];
  spansMultipleCounties: boolean;
  censusName: string | null;
  placeFips: string | null;
  population2024Census: number | null;
  growthPct2020to2024: number | null;
  directClaims: number;
  uniqueClaims: number;
  indexable: boolean;
  buildVerdict: BuildVerdict;
  caveat: string | null;
}

export const county = {
  "id": "county:ada",
  "name": "Ada County",
  "slug": "sell-my-house-fast-ada-county",
  "population2024Census": 535799,
  "population2024Compass": 557590,
  "directClaims": 45,
  "uniqueClaims": 24,
  "indexable": true
} as const;

export const places: Place[] = [
  {
    "id": "city:boise-city",
    "name": "Boise",
    "censusPlaceName": "Boise City",
    "slug": "sell-my-house-fast-boise-id",
    "placeType": "CITY",
    "counties": [
      "Ada County"
    ],
    "spansMultipleCounties": false,
    "censusName": "Boise City city",
    "placeFips": "08830",
    "population2024Census": 237963,
    "growthPct2020to2024": 1,
    "directClaims": 20,
    "uniqueClaims": 15,
    "indexable": true,
    "buildVerdict": "BUILD",
    "caveat": null
  },
  {
    "id": "city:meridian",
    "name": "Meridian",
    "censusPlaceName": "Meridian",
    "slug": "sell-my-house-fast-meridian-id",
    "placeType": "CITY",
    "counties": [
      "Ada County"
    ],
    "spansMultipleCounties": false,
    "censusName": "Meridian city",
    "placeFips": "52120",
    "population2024Census": 139740,
    "growthPct2020to2024": 18.6,
    "directClaims": 7,
    "uniqueClaims": 1,
    "indexable": false,
    "buildVerdict": "RENDER_NOINDEX",
    "caveat": null
  },
  {
    "id": "city:eagle",
    "name": "Eagle",
    "censusPlaceName": "Eagle",
    "slug": "sell-my-house-fast-eagle-id",
    "placeType": "CITY",
    "counties": [
      "Ada County"
    ],
    "spansMultipleCounties": false,
    "censusName": "Eagle city",
    "placeFips": "23410",
    "population2024Census": 33451,
    "growthPct2020to2024": 7.4,
    "directClaims": 9,
    "uniqueClaims": 4,
    "indexable": true,
    "buildVerdict": "BUILD",
    "caveat": null
  },
  {
    "id": "city:kuna",
    "name": "Kuna",
    "censusPlaceName": "Kuna",
    "slug": "sell-my-house-fast-kuna-id",
    "placeType": "CITY",
    "counties": [
      "Ada County"
    ],
    "spansMultipleCounties": false,
    "censusName": "Kuna city",
    "placeFips": "44290",
    "population2024Census": 29127,
    "growthPct2020to2024": 21,
    "directClaims": 11,
    "uniqueClaims": 4,
    "indexable": true,
    "buildVerdict": "BUILD",
    "caveat": null
  },
  {
    "id": "city:star",
    "name": "Star",
    "censusPlaceName": "Star",
    "slug": "sell-my-house-fast-star-id",
    "placeType": "CITY",
    "counties": [
      "Ada County",
      "Canyon County"
    ],
    "spansMultipleCounties": true,
    "censusName": "Star city",
    "placeFips": "76870",
    "population2024Census": 18208,
    "growthPct2020to2024": 61.4,
    "directClaims": 13,
    "uniqueClaims": 8,
    "indexable": true,
    "buildVerdict": "BUILD",
    "caveat": "SPANS 2 COUNTIES (Ada County, Canyon County). Never describe as wholly within Ada County. Jurisdiction-dependent facts must be qualified by which county part is meant."
  },
  {
    "id": "city:garden-city",
    "name": "Garden City",
    "censusPlaceName": "Garden City",
    "slug": "sell-my-house-fast-garden-city-id",
    "placeType": "CITY",
    "counties": [
      "Ada County"
    ],
    "spansMultipleCounties": false,
    "censusName": "Garden City city",
    "placeFips": "29620",
    "population2024Census": 12936,
    "growthPct2020to2024": 5.1,
    "directClaims": 8,
    "uniqueClaims": 4,
    "indexable": true,
    "buildVerdict": "BUILD",
    "caveat": null
  },
  {
    "id": "city:hidden-spring",
    "name": "Hidden Spring",
    "censusPlaceName": "Hidden Spring",
    "slug": "sell-my-house-fast-hidden-spring-id",
    "placeType": "CENSUS_DESIGNATED_PLACE",
    "counties": [
      "Ada County"
    ],
    "spansMultipleCounties": false,
    "censusName": "Hidden Spring CDP",
    "placeFips": "37500",
    "population2024Census": null,
    "growthPct2020to2024": null,
    "directClaims": 0,
    "uniqueClaims": 0,
    "indexable": false,
    "buildVerdict": "DO_NOT_BUILD",
    "caveat": null
  }
];

export const indexablePlaces = places.filter((p) => p.indexable);
export const renderablePlaces = places.filter((p) => p.buildVerdict !== "DO_NOT_BUILD");

export function placeBySlug(slug: string): Place | undefined {
  return places.find((p) => p.slug === slug);
}
