/**
 * GENERATES src/data/claims.ts from the approved claim registry.
 *
 * Only claims with approvedForPublication=true cross into the application, and
 * each carries its source title and URL so a rendered fact always ships with
 * its attribution. Withheld and disputed claims cannot reach a page because
 * they are not in the generated file at all.
 */
import { readFileSync, writeFileSync } from "node:fs";

const reg = JSON.parse(readFileSync("data/idaho/evidence/ada-claims.json", "utf8"));
const sources = JSON.parse(readFileSync("data/idaho/sources/ada-county-sources.json", "utf8")).sources;
const srcById = Object.fromEntries(sources.map((s) => [s.id, s]));

const approved = reg.claims.filter((c) => c.approvedForPublication).map((c) => ({
  id: c.id,
  claim: c.claim,
  quote: c.quotedLanguage ?? null,
  entities: c.entity ?? [],
  topics: c.topic ?? [],
  confidence: c.confidence,
  verifiedOn: c.verifiedOn,
  // A rendered fact must ship with somewhere to check it.
  sources: (c.sourceIds ?? [])
    .map((id) => srcById[id])
    .filter(Boolean)
    .map((s) => ({ title: s.title, url: s.url, publisher: s.publisher, tier: s.sourceTier })),
  verificationFlag: c.verificationFlag ?? null,
  temporalStatus: c.temporalStatus ?? null,
  jurisdiction: c.jurisdiction ?? null,
  amendmentHistory: c.amendmentHistory ?? null,
}));

const withFlag = approved.filter((c) => c.verificationFlag);

const out = `// GENERATED by scripts/codegen/build-claims.mjs — DO NOT EDIT.
// Regenerate: node scripts/codegen/build-claims.mjs
//
// ONLY approved claims are emitted. A withheld or disputed claim cannot reach a
// page because it is not in this file. Every claim carries its sources so a
// rendered fact always ships with a way to check it.

export interface ClaimSource {
  title: string;
  url: string;
  publisher: string;
  tier: number;
}

export interface Claim {
  id: string;
  claim: string;
  quote: string | null;
  entities: string[];
  topics: string[];
  confidence: string;
  verifiedOn: string;
  /** CURRENT unless the claim describes a fixed past period. Rendered when not CURRENT. */
  temporalStatus: string | null;
  /**
   * The scope the claim applies to — 'Idaho' and 'Boise, Idaho' are materially
   * different things to a reader. Set on all 80 residential claims and dropped
   * by this generator until 2026-09-11, so EvidenceAppendix rendered the scope
   * on commercial pages and nothing on residential ones, from the same
   * component. Nothing looked broken; the line just ended earlier.
   */
  jurisdiction: string | null;
  /** The Idaho Code compiler's own history note, verbatim. Rendered per source. */
  amendmentHistory: string | null;
  sources: ClaimSource[];
  /** Set when the claim needs re-verification before it may be published. */
  verificationFlag: string | null;
}

export const claims: Claim[] = ${JSON.stringify(approved, null, 2)};

const byId = new Map(claims.map((c) => [c.id, c]));

export function claim(id: string): Claim | undefined {
  return byId.get(id);
}

/** Claims safe to render right now — flagged ones are held back. */
export function publishable(list: Claim[]): Claim[] {
  return list.filter((c) => c.verificationFlag === null);
}

export function claimsForEntity(entityId: string): Claim[] {
  return publishable(claims.filter((c) => c.entities.includes(entityId)));
}

/** Claims naming ONLY this entity — what can differentiate its page. */
export function claimsUniqueTo(entityId: string): Claim[] {
  return publishable(
    claims.filter((c) => c.entities.length === 1 && c.entities[0] === entityId)
  );
}

export function claimsByTopic(topic: string): Claim[] {
  return publishable(claims.filter((c) => c.topics.includes(topic)));
}
`;
writeFileSync("src/data/claims.ts", out);
console.log(`claims.ts: ${approved.length} approved claims emitted`);
console.log(`  carrying a verification flag (held back at render): ${withFlag.length}`);
for (const c of withFlag) console.log(`    ${c.id} — ${c.verificationFlag}`);
